# Generated by Django 3.2.9 on 2021-11-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog',
            new_name='content',
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.TextField(default='Empty', max_length=125),
            preserve_default=False,
        ),
    ]
