# Generated by Django 3.2.9 on 2021-12-06 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20211129_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=512)),
                ('status', models.BooleanField(default=False)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.blog')),
            ],
        ),
    ]
