# Generated by Django 3.2.9 on 2021-12-15 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_alter_blog_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='publish_date',
        ),
    ]
