# Generated by Django 3.2.9 on 2021-12-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_blog_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='create_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
